### ISSUE TITLE
astroid.exceptions.AstroidError with pylint 2.16.1

### ISSUE THREAD

**Issue by hyunhoRIDI** [Enforcer/pylint_google_style_guide_imports_enforcing#5]
python version: 3.10.9
pylint version: 2.16.1
pylint_google_style_guide_imports_enforcing version: 1.3.0

I think there is some compatibility problem with those versions.

```
Traceback (most recent call last):
  File "/Users/hyunholee/.pyenv/versions/data-etl-env/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/Users/hyunholee/.pyenv/versions/3.10.9/envs/data-etl-env/lib/python3.10/site-packages/pylint/__init__.py", line 36, in run_pylint
    PylintRun(argv or sys.argv[1:])
  File "/Users/hyunholee/.pyenv/versions/3.10.9/envs/data-etl-env/lib/python3.10/site-packages/pylint/lint/run.py", line 213, in __init__
    linter.check(args)
  File "/Users/hyunholee/.pyenv/versions/3.10.9/envs/data-etl-env/lib/python3.10/site-packages/pylint/lint/pylinter.py", line 681, in check
    check_parallel(
  File "/Users/hyunholee/.pyenv/versions/3.10.9/envs/data-etl-env/lib/python3.10/site-packages/pylint/lint/parallel.py", line 156, in check_parallel
    for (
  File "/Users/hyunholee/.pyenv/versions/3.10.9/lib/python3.10/concurrent/futures/process.py", line 570, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/Users/hyunholee/.pyenv/versions/3.10.9/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
    yield _result_or_cancel(fs.pop())
  File "/Users/hyunholee/.pyenv/versions/3.10.9/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "/Users/hyunholee/.pyenv/versions/3.10.9/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/Users/hyunholee/.pyenv/versions/3.10.9/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
astroid.exceptions.AstroidError
error Command failed with exit code 1.
```

**Comment by hyunhoRIDI** [comment]
FYI, I'm using astroid==2.14.1
